// Code generated by MockGen. DO NOT EDIT.
// Source: seller.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
)

// MockSeller is a mock of Seller interface.
type MockSeller struct {
	ctrl     *gomock.Controller
	recorder *MockSellerMockRecorder
}

// MockSellerMockRecorder is the mock recorder for MockSeller.
type MockSellerMockRecorder struct {
	mock *MockSeller
}

// NewMockSeller creates a new mock instance.
func NewMockSeller(ctrl *gomock.Controller) *MockSeller {
	mock := &MockSeller{ctrl: ctrl}
	mock.recorder = &MockSellerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeller) EXPECT() *MockSellerMockRecorder {
	return m.recorder
}
